# Generated by Django 3.1.8 on 2021-05-26 13:45

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workplace",
            name="address",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.FileField(
                blank=True, default="default_avatar.png", null=True, upload_to=""
            ),
        ),
        migrations.AddField(
            model_name="workplace",
            name="city",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="workplace",
            name="country",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="workplace",
            name="image",
            field=models.FileField(
                blank=True, default="default_place_of_work.png", null=True, upload_to=""
            ),
        ),
        migrations.AddField(
            model_name="workplace",
            name="phone_number",
            field=phone_field.models.PhoneField(
                blank=True, help_text="Contact phone number", max_length=31
            ),
        ),
        migrations.AddField(
            model_name="workplace",
            name="street",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
