# Generated by Django 3.1.8 on 2021-05-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_auto_20210526_1351"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyWord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name="article",
            name="scopus_indication",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="key_words",
            field=models.ManyToManyField(blank=True, to="articles.KeyWord"),
        ),
    ]
